baseurl = "http://sample-castanet.netlify.com/mysite/"
languageCode = "en-us"
title = "Geração Foda-se"
theme = "castanet"
googleAnalytics = ""
disqusShortname = ""
paginate = "9"


[permalinks]
	# page = "/:filename/"
	about = "/:filename/"
	episode = "/:filename/"


# The theme supports menus with up to one submenu per menu item
# The menu name must be "Main"
# The menus are sorted based upon their identifier
[[Menu.Main]]
    name = "Sobre"
    identifier = "about"
    url = "about"

[[Menu.Main]]
    name = "Contatos"
    identifier = "contact"
    url = "contact"

[[Menu.Main]]
    name = "Convidados"
    identifier = "guests"
    url = "guest"


[params]
site_theme = "grey"
# site_layout = "grid"
site_layout = "grid"
enable_jumbo = "true"
# enable_jumbo = "false"
# truncate = "100"
# about_logo = "/img/logo.jpg"
copyright_notice = "Copyright 2016 [Matt Stratton](https://www.mattstrattion.io)"
itunes_subscribe = "http://itunes.apple.com/us/podcast/arrested-devops/id773888088?mt=2&uo=4&at=11lsCi"
android_subscribe = "http://subscribeonandroid.com/feeds.podtrac.com/VGAulpN7MY1U"
google_play_subscribe = "https://goo.gl/app/playmusic?ibi=com.google.PlayMusic&isi=691797987&ius=googleplaymusic&link=https://play.google.com/music/m/Ihj4yege3lfmp3vs5yoopgxijpi?t%3DArrested_DevOps"
stitcher_subscribe = "http://www.stitcher.com/podcast/arrested-devops-2/arrested-devops"
soundcloud_subscribe = "http://feeds.soundcloud.com/users/soundcloud:users:203144248/sounds.rss"
pocketcasts_subscribe = "http://pcasts.in/feed/feeds.soundcloud.com/users/soundcloud:users:203144248/sounds.rss"
mailchimp_subscribe = "//arresteddevops.us3.list-manage.com/subscribe/post?u=5e4cbcac996bb9df25f970a89&amp;id=154fa76bcc"
#rss_subscribe = "http://feed.com/myfeed" #only set this if you don't want to use the built-in feed
description = "A Proposta do podcast Geração fodase é entrevistar pessoas que tocaram o foda-se para as expectativas da sociedade em algum momento (todo empreendedor em essência faz isso), e contar o lado negro do empreendedorismo. E entender os desafios que existem além do empreendedorismo de palco e agregar conteúdo de valor e lições que podem ser compartilhadas. Tudo isso sem mimimi, sem o politicamente correto e sem medir palavrões."
media_prefix = "https://media.blubrry.com/arresteddevops/content.blubrry.com/arresteddevops/"
  [params.feed]
    copyright = "Copyright 2016 Matt Stratton" #do not use markdown in this field; it is used in the feed
    itunes_subtitle = "The best podcast ever" #no markdown or HTML
    itunes_author = "Matt Stratton" #no markdown or HTML
    itunes_summary = "Geração fodase é entrevistar pessoas que tocaram o foda-se para as expectativas da sociedade em algum momento (todo empreendedor em essência faz isso), e contar o lado negro do empreendedorismo. E entender os desafios que existem além do empreendedorismo de palco e agregar conteúdo de valor e lições que podem ser compartilhadas. Tudo isso sem mimimi, sem o politicamente correto e sem medir palavrões." # Limited to 4000 characters or less, plain text, no HTML
    itunes_owner_name = "Matt Stratton"
    itunes_owner_email = "matt.stratton@gmail.com" #contains the e-mail address that will be used to contact the owner of the Podcast for communication specifically about their Podcast on iTunes. It will not be publicly displayed on iTunes.
    itunes_image = "../img/logo.jpg" #fqdn to the image art for your podcast
    itunes_top_category = "Technology"
    itunes_first_sub_category = "Software How-To"
    itunes_second_sub_category = "Tech News"
    language = "en-us"

  [params.social]
    github = "arresteddevops"
    gitlab = "mattstratton"
    facebook = "Arresteddevops"
    facebook_admin = ["500557137","1234"] # This needs to be one or more page admins to get domain insights
    twitter = "arresteddevops"
    twitter_domain = "arresteddevops.com" # This domain shows in twitter cards as "View on `twitter_domain`"
    googleplus = "ArrestedDevOps"
    pinterest = "nozzleio"
    instagram = "nozzleio"
    youtube = "arresteddevops"
    linkedin = "mattstratton"

  [params.authors]
    [params.authors.Matt]
      name	= "Mateus Santos"
      thumbnail = "img/host/mateus-oliver.jpg"
      bio = "Matt Stratton is a solutions architect at Chef, where he demonstrates how Chef’s automation platform provides speed and flexibility to clients’ infrastructure. He is devoted to concepts like Continuous Delivery and Infrastructure as Code, and his license plate actually says “DevOps”. He lives in Chicago and has an unhealthy obsession with Doctor Who, Firefly, and Game of Thrones. And whiskey."
      [params.authors.Matt.social]
        github = "mattstratton"
        facebook = "matt.stratton"
        twitter = "mattstratton"
        linkedin = "mattstratton"
        homepage = "https://www.mattstratton.io"
        pinterest = "mattstratton"
        instagram = "instagram"
        youtube = "mattstratton"
    [params.authors.Trevor]
			name = "Mateus Santos"
			thumbnail = "img/host/Tiago.jpg"
			bio = ""
				[params.authors.Trevor.social]
					twitter = "trevorghess"
   

    [params.links]
      [params.links.ado]
        name = "Arrested DevOps"
        url = "https://www.arresteddevops.com"
      [params.links.ffs]
        name = "Food Fight Show"
        url = "https://foodfightshow.org"
      [params.links.sdt]
        name = "Software Defined Talk"
        url = "https://cote.io/podcasts/sdt/"
